root = "." 
tmp_dir = "tmp"  

[build]   
  cmd = "go build -o tmp/main cmd/server/main.go"   
  bin = "tmp/main"
  full_bin = ""
  delay = 1000   
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]   
  include_dir = ["cmd", "internal"]   
  include_ext = ["go", "tpl", "tmpl", "html"]   
  send_interrupt = true   
  rerun_delay = 500   
  stop_on_error = false  

[log]
  time = false

[color]   
  build = "yellow"   
  main = "magenta"   
  runner = "green"   
  watcher = "cyan"  

[screen]   
  keep_scroll = true